# Generated by Django 4.2.1 on 2023-05-31 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('addDate', models.DateField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
