# Generated by Django 4.2.1 on 2023-05-17 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('addDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.IntegerField(max_length=1)),
            ],
        ),
    ]
