# Generated by Django 4.2.1 on 2023-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_task_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
